Repository Kuadrant/kuadrant-console-plugin, pull requests merged in 2024-10, with the labels that each got.

#85 README updates
  README.md
Labels: approved, lgtm

#79 Gh 59- Update flow
  console-extensions.json
  locales/en/plugin__console-plugin-template.json
  src/components/DropdownWithKebab.tsx
  src/components/KuadrantCreateUpdate.tsx
  src/components/KuadrantDNSPolicyCreatePage.tsx
  src/components/KuadrantRateLimitPolicyCreatePage.tsx
  src/components/KuadrantTLSCreatePage.tsx
  src/components/gateway/GatewaySelect.tsx
  src/components/issuer/clusterIssuerSelect.tsx
  src/components/issuer/issuerSelect.tsx
  src/components/issuer/types.ts
  src/components/namespace/NamespaceSelect.tsx
  src/utils/createResource.tsx
Labels: approved, do-not-merge/work-in-progress

#94 Some UI fixes
  src/components/KuadrantDNSPolicyCreatePage.tsx
  src/components/KuadrantPoliciesPage.tsx
  src/components/ResourceList.tsx
  src/components/kuadrant.css
Labels: approved, lgtm

#93 Dynamic lookup for topology
  Dockerfile
  README.md
  entrypoint.sh
  install.yaml
  src/components/PolicyTopologyPage.tsx
Labels: approved, lgtm

#97 Add global picker for: AuthPolicy, TLSPolicy and RateLimitPolicy
  src/components/KuadrantAuthPolicyCreatePage.tsx
  src/components/KuadrantPoliciesPage.tsx
  src/components/KuadrantRateLimitPolicyCreatePage.tsx
  src/components/KuadrantTLSCreatePage.tsx
Labels: approved, lgtm

#99 Some UI Fixes
  src/components/ResourceList.tsx
  src/components/kuadrant.css
Labels: approved, lgtm

#98 Gh 88
  console-extensions.json
  src/components/DropdownWithKebab.tsx
  src/components/KuadrantCreateUpdate.tsx
  src/components/KuadrantDNSPolicyCreatePage.tsx
  src/components/KuadrantTLSCreatePage.tsx
  src/components/PolicyTopologyPage.tsx
  src/components/dnspolicy/HealthCheckField.tsx
  src/components/dnspolicy/LoadBalancingField.tsx
  src/components/dnspolicy/types.ts
  src/components/namespace/NamespaceSelect.tsx
  src/utils/modelUtils.ts
Labels: approved, lgtm

#103 Remove form view from RLP until 1.x
  src/components/DropdownWithKebab.tsx
  src/components/KuadrantRateLimitPolicyCreatePage.tsx
Labels: approved, lgtm

#109 remove package-lock.json - only use yarn for deps
  package-lock.json
Labels: approved

#111 Policy topology fixes, centralise CRD versioning refs
  console-extensions.json
  install.yaml
  src/components/KuadrantAuthPolicyCreatePage.tsx
  src/components/KuadrantDNSPolicyCreatePage.tsx
  src/components/KuadrantOverviewPage.tsx
  src/components/KuadrantPoliciesPage.tsx
  src/components/KuadrantRateLimitPolicyCreatePage.tsx
  src/components/KuadrantTLSCreatePage.tsx
  src/components/PolicyTopologyPage.tsx
  src/utils/latest.tsx
Labels: approved, lgtm

#112 all policies create button & added emptystate views to empty resources
  locales/en/plugin__kuadrant-console-plugin.json
  src/components/KuadrantPoliciesPage.tsx
  src/components/PolicyTopologyPage.tsx
  src/components/ResourceList.tsx
  src/components/dnspolicy/HealthCheckField.tsx
  src/components/dnspolicy/LoadBalancingField.tsx
  src/components/kuadrant.css
Labels: approved, lgtm

#120 consoleplugin v1
  install.yaml
Labels: approved, lgtm

#122 tmp
  .github/workflows/build.yaml
  .github/workflows/issues.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
Labels: approved

#123 actions: fixup
  .github/workflows/build.yaml
  .github/workflows/issues.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
Labels: approved

#134 adding create resource button to overview page
  .github/workflows/i18n.yaml
  locales/en/plugin__kuadrant-console-plugin.json
  src/components/KuadrantOverviewPage.tsx
  src/components/kuadrant.css
Labels: approved, lgtm

#138 removing info box
  locales/en/plugin__kuadrant-console-plugin.json
  src/components/KuadrantPoliciesPage.tsx
Labels: approved, lgtm

#131 GW status: enforced if affected by any policies succesfully
  src/components/ResourceList.tsx
Labels: approved, lgtm

#130 dockerfile updates
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: approved, lgtm

#132 Overview: edit Gateway/HTTPRoutes links broken
  src/components/DropdownWithKebab.tsx
Labels: approved, lgtm

#137 DNS Policy form fix and load balancing fix
  locales/en/plugin__kuadrant-console-plugin.json
  src/components/KuadrantDNSPolicyCreatePage.tsx
  src/components/KuadrantTLSCreatePage.tsx
  src/components/dnspolicy/HealthCheckField.tsx
  src/components/dnspolicy/LoadBalancingField.tsx
  src/components/dnspolicy/types.ts
  src/components/kuadrant.css
Labels: approved, lgtm

#135 Adding tooltips for status labels
  locales/en/plugin__kuadrant-console-plugin.json
  src/components/ResourceList.tsx
Labels: approved, lgtm

#139 topology: add gatewayclass filtering
  src/components/PolicyTopologyPage.tsx
Labels: enhancement, approved, lgtm, policy-topology
